# Generated by Django 4.2.2 on 2023-06-28 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='name')),
                ('about_publisher', models.TextField(max_length=1000, verbose_name='about_publisher')),
            ],
            options={
                'verbose_name': 'publisher',
                'verbose_name_plural': 'publishers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='name')),
            ],
            options={
                'verbose_name': 'type',
                'verbose_name_plural': 'types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='title')),
                ('image', models.ImageField(upload_to='board_game/game_images', verbose_name='image')),
                ('player_count', models.CharField(max_length=50, verbose_name='player_count')),
                ('duration', models.CharField(max_length=50, verbose_name='duration')),
                ('player_age', models.CharField(max_length=50, verbose_name='player_age')),
                ('language', models.CharField(choices=[('EN', 'EN'), ('LT', 'LT'), ('RU', 'RU'), ('PL', 'PL'), ('Other', 'Other')], db_index=True, default='LT', max_length=50, verbose_name='languages')),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard'), ('Extreme', 'Extreme'), ('Nightmare', 'Nightmare')], db_index=True, default='Medium', max_length=50, verbose_name='difficulty')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='board_game.publisher', verbose_name='publishers')),
                ('type', models.ManyToManyField(to='board_game.type', verbose_name='type(s)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'game',
                'verbose_name_plural': 'games',
                'ordering': ['title'],
            },
        ),
    ]
