# Generated by Django 4.2.2 on 2023-06-29 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='type',
        ),
        migrations.AddField(
            model_name='game',
            name='category',
            field=models.ManyToManyField(to='board_game.type', verbose_name='category(-ies)'),
        ),
        migrations.AddField(
            model_name='game',
            name='year',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='year'),
        ),
    ]
