# Generated by Django 4.2.2 on 2023-06-29 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_game', '0004_gameborrowrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameborrowrequest',
            name='due_back',
            field=models.DateField(blank=True, null=True, verbose_name='due back'),
        ),
        migrations.AddField(
            model_name='gameborrowrequest',
            name='status',
            field=models.CharField(blank=True, choices=[('Available', 'Available'), ('Reserved', 'Reserved'), ('Borrowed', 'Borrowed')], default='Available', max_length=20, verbose_name='status'),
        ),
    ]
