# Generated by Django 4.2.2 on 2023-06-29 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_game', '0005_gameborrowrequest_due_back_gameborrowrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameborrowrequest',
            name='due_back',
            field=models.DateField(blank=True, null=True, verbose_name='due_back'),
        ),
    ]
