# Generated by Django 4.2.2 on 2023-06-30 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_game', '0007_game_rating_gamerating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameborrowrequest',
            name='status',
        ),
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.CharField(blank=True, choices=[('Available', 'Available'), ('Borrowed', 'Borrowed')], default='Available', max_length=20, verbose_name='status'),
        ),
    ]
