# Generated by Django 4.2.2 on 2023-06-30 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_game', '0008_remove_gameborrowrequest_status_game_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameborrowrequest',
            name='pick_up_place',
            field=models.CharField(blank=True, choices=[('Physical Exchange', 'Physical Exchange'), ('Game Store', 'Game Store'), ('Post', 'Post'), ('Pick-up Terminal', 'Pick-up Terminal')], max_length=20, null=True, verbose_name='pick-up place'),
        ),
    ]
