# Generated by Django 4.2.2 on 2023-07-04 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_game', '0010_parcelmachine_partnergamestore_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
