# Generated by Django 4.2.2 on 2023-07-04 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_game', '0011_game_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameborrowrequest',
            name='address',
        ),
        migrations.RemoveField(
            model_name='gameborrowrequest',
            name='is_accepted',
        ),
        migrations.RemoveField(
            model_name='gameborrowrequest',
            name='parcel_machine',
        ),
        migrations.RemoveField(
            model_name='gameborrowrequest',
            name='partner_game_store',
        ),
        migrations.RemoveField(
            model_name='gameborrowrequest',
            name='pick_up_place',
        ),
        migrations.AddField(
            model_name='gameborrowrequest',
            name='accepted',
            field=models.BooleanField(default=False, verbose_name='accepted'),
        ),
        migrations.AddField(
            model_name='gameborrowrequest',
            name='returned',
            field=models.BooleanField(default=False, verbose_name='returned'),
        ),
        migrations.DeleteModel(
            name='ParcelMachine',
        ),
        migrations.DeleteModel(
            name='PartnerGameStore',
        ),
    ]
