# Generated by Django 4.2.2 on 2023-07-07 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_game', '0012_remove_gameborrowrequest_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameborrowrequest',
            name='accepted',
        ),
        migrations.AddField(
            model_name='gameborrowrequest',
            name='request_status',
            field=models.CharField(choices=[('New', 'New'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], db_index=True, default='New', max_length=10, verbose_name='request_status'),
        ),
    ]
